### ISSUE TITLE
Feature request - Show snake length on the UI

### ISSUE THREAD

**Issue by tflinz** [sendwithus/battlesnake-server#13]
On the right hands side, by the health.
show the current snake length.
pleeease :)

**Comment by daniel-swu** [comment]
@tflinz What are some the reasons for this data? We have some concerns that the ui is already very busy and before adding any additional information here, we need a strong use case for it.

**Comment by slashterix** [comment]
I think this would be helpful when debugging your snake, but not great for the actual tournament.

Might be a "game setting" to show per move taunts and/or snake lengths? Clutter up the UI for local testing, but not on game day.

**Comment by exzizt** [comment]
I am neutral about this, being one who both favours neat and tidy displays as well as the display of useful information. Actually, in the 2017 server I used taunts to display the length (as well as other info):

![image](https://user-images.githubusercontent.com/17113094/36302196-74f72dc6-12bc-11e8-9fe5-2e6261101239.png)

Sure, I can print this info to debug output, but of course, it is very convenient to display it in the UI.

I think that showing the snake length in the UI would be good because if snakes are roughly the same length it's difficult to tell which is longer/shorter. I imagine a scenario during the tournaments where two snakes are nearing in on a head-on collision, but no one can express woe or excitement with certainty because they can't be certain about each snake's length. Maybe the mystery and suspense is wanted? I don't know.

**Comment by brandon-swu** [comment]
This isn’t something we’re going to add to the server for this year as the data is already returned in the API. If this is something you want to see I suggest using a logging service like Papertrail or at the very least tailing your snake server log, and having this open while you’re running your snake
