### ISSUE TITLE
Should have way to validate request is from the "real" game server

### ISSUE THREAD

**Issue by sjmcgrath** [sendwithus/battlesnake-server#47]
There should be a way for a Snake server to validate that a request comes from the "real" game server. The game server making HTTPS requests using an SSL client certificate seems like a reasonable possibility.

**Comment by brandon-swu** [comment]
This is definitely something we've talked about before, because as a snake technically you could discover where the other snakes are on the board and "poison" them with bad game state to get them on a disadvantage. I'll keep this around for next year but I don't think this is something we're going to get to before the event. Thanks @sjmcgrath !
