### ISSUE TITLE
Your snake (You) is sent twice

### ISSUE THREAD

**Issue by exzizt** [sendwithus/battlesnake-server#5]
From: https://github.com/battle-snake/battle_snake/issues/31

Since this year your snake (You) is sent over as a Snake object (and not an id used to identify your snake in the Snakes list), I don't think it is necessary to send over your snake again in the Snakes list.

```
``interface World {
  object: 'world';
  id: number;
  you: Snake; # Your snake
  snakes: List<Snake>; # Contains your snake again
  height: number;
  width: number;
  turn: number;
  food: List<Point>;
}``
```

This is a minor optimization, but it will be removing redundancy and therefore reducing the size of the JSON string.

Edit: Maybe "snakes" could be called "other_snakes".

**Comment by robbles** [comment]
It'll be easier to write logic that avoids snake bodies if your snake is kept in the list.

You do need to avoid your own body as well as the other snakes.

**Comment by daniel-swu** [comment]
Yeah you are correct this it is redundant, but it's also helpful, because you don't need to parse your own snake out of the list based on an id. Also we're not worried about the extra size in the payload, so we will be leaving this in for this year.

Again thanks for the issue, and keep bringing up anything you think of in relation to the server
